# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Meanscompute <- function(X_data, y_data, Nclasses, p) {
    .Call(`_solda_Meanscompute`, X_data, y_data, Nclasses, p)
}

Predictions_lambdasolo <- function(Means_mat, y_data, X_new, Nclasses, Theta_lambda) {
    .Call(`_solda_Predictions_lambdasolo`, Means_mat, y_data, X_new, Nclasses, Theta_lambda)
}

CV_Ensemble_EN <- function(X_data, y_data, lambdas_grid, Nclasses, num_folds, tolerance, max_iter, num_threads, MV_matrix) {
    .Call(`_solda_CV_Ensemble_EN`, X_data, y_data, lambdas_grid, Nclasses, num_folds, tolerance, max_iter, num_threads, MV_matrix)
}

Ensemble_EN_Opt <- function(X_data, Means_matrix, lambdas_sparsity, lambda_diversity, num_groups, tolerance, max_iter, MV_matrix) {
    .Call(`_solda_Ensemble_EN_Opt`, X_data, Means_matrix, lambdas_sparsity, lambda_diversity, num_groups, tolerance, max_iter, MV_matrix)
}

